# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

calculate_mi_and_omes <- function(i, j, P2, P1, q, N) {
    .Call('_CMA_calculate_mi_and_omes', PACKAGE = 'CMA', i, j, P2, P1, q, N)
}

Compute_C <- function(Pij, Pi, N, q) {
    .Call('_CMA_Compute_C', PACKAGE = 'CMA', Pij, Pi, N, q)
}

hammingdist <- function(X) {
    .Call('_CMA_hammingdist', PACKAGE = 'CMA', X)
}

AccPi_true <- function(align, W, N, q, M) {
    .Call('_CMA_AccPi_true', PACKAGE = 'CMA', align, W, N, q, M)
}

AccPij_true <- function(align, W, N, q, M) {
    .Call('_CMA_AccPij_true', PACKAGE = 'CMA', align, W, N, q, M)
}

arrayC <- function(input, dim) {
    .Call('_CMA_arrayC', PACKAGE = 'CMA', input, dim)
}

